version: 2.1

jobs:
  compile-linux-community:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: large
    steps:
      - run:
          name: Install required software
          command: |
            sudo apt-get update
            sudo apt-get install libssl-dev gcc-10 g++-10 snapd ccache flex bison
      - run:
          name: Checkout Source
          command: |
            cd ..
            git clone --no-tags --depth 1 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH" project
      - restore_cache:
          keys:
            - ccache-v1-{{ .Branch }}-{{ .Revision }}
            - ccache-v1-{{ .Branch }}-
            - ccache-v1-
      - run:
          name: Zero CCache Statistics
          command: ccache -z
      - run:
          name: Create build directories
          command: |
            mkdir -p build
      - run:
          name: Configure
          command: |
            cd build
            cmake .. -DUSE_SEPARATE_REPLICATION2_TESTS_BINARY=On -DUSE_MAINTAINER_MODE=On -DCMAKE_C_COMPILER=/usr/lib/ccache/gcc-10 -DCMAKE_CXX_COMPILER=/usr/lib/ccache/g++-10
      # -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      - run:
          name: Build
          command: |
            cd build
            cmake --build . --target arangodbtests_replication2 arangod arangosh arangobench arangodump arangorestore -- -j $(nproc)
      - run:
          name: CCache Statistics
          command: ccache -s
      - store_artifacts:
          path: build/bin
      - save_cache:
          when: always
          key: ccache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/circleci/.ccache
      - persist_to_workspace:
          root: .
          paths:
            - build/bin
            - scripts/
            - js/
            - etc/
            - tests/js
            - utils
            - UnitTest

  replication-two-gtest:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run GTest
          command: |
            build/bin/arangodbtests_replication2 --gtest_output=xml
      - store_test_results:
          path: test-details.xml

  replication-two-server-tests:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run GTest
          command: |
            scripts/unittest replication2_server --cluster true --cleanup false --writeXmlReport true --dumpAgencyOnError true
      - store_artifacts:
          destination: replication2_server
          path: out/*
      - store_artifacts:
          destination: replication2_server
          path: /tmp/*


workflows:
  replication-two-pr:
    jobs:
      - compile-linux-community
      - replication-two-gtest:
          requires:
            - compile-linux-community
      - replication-two-server-tests:
          requires:
            - compile-linux-community
