version: 2.1

jobs:
  compile-linux-community:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: large
    steps:
      - run:
          name: Install required software
          command: |
            - sudo apt-get update
            - sudo apt-get install libssl-dev
      - restore_cache:
            keys:
              - source-v1-{{ .Branch }}
              - source-v1-{{ .Branch }}
              - source-v1-
      - checkout
      - save_cache:
          name: git cache
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - cmake-v1-{{ .Branch }}-{{ .Revision }}
            - cmake-v1-{{ .Branch }}-
            - cmake-v1-
      - run:
          name: Create build directories
          command: |
            mkdir -p build
      - run:
          name: Configure
          command: |
            cd build
            cmake .. -DUSE_MAINTAINER_MODE=On
      - run:
          name: Build
          command: |
            cd build
            cmake --build . -- -j $(nproc)
      - store_artifacts:
          path: build/bin
      - save_cache:
          key: cmake-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - build

workflows:
  compile-linux-community:
    jobs:
      - compile-linux-community
