version: 2.1

jobs:
  compile-linux-community:
    docker:
      - image: arangodb/ubuntubuildarangodb5-x86_64:latest
    steps:
      - restore_cache:
            keys:
              - source-v1-{{ .Branch }}
              - source-v1-{{ .Branch }}
              - source-v1-
      - checkout
      - save_cache:
          name: git cache
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - cmake-v1-{{ .Branch }}-{{ .Revision }}
            - cmake-v1-{{ .Branch }}-
            - cmake-v1-
      - run:
          name: Create build directories
          command: |
            mkdir -p build
      - run:
          name: Configure
          command: |
            cd build
            cmake .. -DUSE_MAINTAINER_MODE=On -DCMAKE_LIBRARY_PATH=/opt/openssl-1.1.1/lib -DOPENSSL_ROOT_DIR=/opt/openssl-1.1.1
      - run:
          name: Build
          command: |
            cd build
            cmake --build . -- -j $(nproc)
      - store_artifacts:
          path: build/bin
      - save_cache:
          key: cmake-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - build

workflows:
  compile-linux-community:
    jobs:
      - compile-linux-community
